name: Push Ordering Contracts Nuget Package to GitHub Package Registry

on:
  push:
    branches:
    - main
    paths:
    - "Reenbit.Ordering/**"
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: "Release"
  DOTNET_VERSION: "8.0.x"
  GITHUB_PACKAGE_REGISTRY_URL: https://nuget.pkg.github.com/reenbit/index.json

jobs:
  nuget-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate build number
        id: build_number
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          bump_each_commit: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: ${{ env.GITHUB_PACKAGE_REGISTRY_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build Reenbit.Ordering.Public.Events/Reenbit.Ordering.Public.Events.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}
          dotnet pack Reenbit.Ordering.Public.Events/Reenbit.Ordering.Public.Events.csproj -c ${{ env.BUILD_CONFIGURATION }}  -p:PackageVersion=${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.patch }}

      - name: nuget publish
        run: |
          dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github ${{ env.GITHUB_PACKAGE_REGISTRY_URL }}
          dotnet nuget push *.Public.*/bin/Release/*.nupkg --skip-duplicate
